version: "3"
services:
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:4.0-xenial
    expose:
    - 27017
    ports:
      - 27011:27017
    restart: always 
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: bruk
      MONGO_INITDB_ROOT_PASSWORD: bruk
  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo:4.0-xenial
    expose:
    - 27017
    ports:
    - 27012:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: bruk
      MONGO_INITDB_ROOT_PASSWORD: bruk

  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo:4.0-xenial
    expose:
    - 27017
    ports:
    - 27013:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: bruk
      MONGO_INITDB_ROOT_PASSWORD: bruk


#  setuprs:
#    image: "setuprs" 
#    build: ./setup
#    depends_on: 
#      - mongo3
#  adminmongo:
#    image: "mrvautin/adminmongo"
#    ports:
#        - 1234:1234